src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - Milestones are significant events in the life-cycle of a Project. You can also use them to track project phases. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - A project can have many milestones.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Predecessor_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The predecessor task for this task if applicable.</inlineHelpText>
        <label>Predecessor Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Milestone1_Task__c.Project_Milestone__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project_Milestone__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Milestone1_Task__c</referenceTo>
        <relationshipLabel>Successor Tasks</relationshipLabel>
        <relationshipName>Successor_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>When should this task start by?</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Milestone1_Project_Creation_Behavior.cls
/*******************************************************************************************************

ShouldAutomaticallyCreateChildProject -  GIVEN an object that needs a project to be created,
                                    WHEN the required fields are populated,
                                    THEN automate the project creation.
                                    
ShouldUpdateProjectKickoffToCurrentDate -   GIVEN a project has been created from a template,
                                            WHEN the project is inserted,
                                            THEN automatically set start date to today.
                                            
ShouldCascadeForwardDateShift - GIVEN an existing project,
								WHEN the project kickoff date is delayed,
								THEN cascade date shift to milestone and tasks.
								
ShouldCascadeBackwardDateShift -    GIVEN an existing project,
									WHEN the project kickoff and deadline dates are rescheduled to an earlier date,
									THEN cascade date shift to milestone and tasks.
									
ShouldAllowNonAdminUsersToCreateProjects - GIVEN an object that needs a project to be created,
										   WHEN the required fields are populated and the user triggering the automated project creation is not an admin,
										   THEN the project should successfully be created. 									

*******************************************************************************************************/


@isTest
public class Milestone1_Project_Creation_Behavior {
    
    private static Account acc = new Account(
    name = 'Test'
    );
    private static Opportunity opp = new Opportunity(
    name = 'test opp',
    StageName = 'Prospecting',
    closeDate = date.today()
    );
    private static Opportunity oldOpp = new Opportunity(
        name = 'test opp',
        StageName = 'Prospecting',
        closeDate = date.today()
        );
    private static Milestone1_Project__c testProject = Milestone1_Test_Utility.sampleProject('Circuit' + System.now());
    
    static testmethod void ShouldAutomaticallyCreateChildProject(){
        Milestone1_Project__c proj = new Milestone1_Project__c();
        list<Milestone1_Milestone__c> Milestones = new list<Milestone1_Milestone__c>();
        list<Milestone1_Task__c> Tasks = new list<Milestone1_Task__c>();
        Milestone1_Project_Creation_Utility projCreationUtil = new Milestone1_Project_Creation_Utility();
        map<id, sObject> oldMap = new map<id, sObject>();
        map<id, sObject> newMap = new map<id, sObject>();
        
        testProject.Kickoff__c = date.today().addDays(-5);
        testProject.Status__c = 'Active';
        insert testProject;
        testProject = [select Id, Name from Milestone1_Project__c where Name = :testProject.Name limit 1];
         
        Milestone1_Milestone__c testMilestone = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'UNIT TEST MILESTONE NAME ACB123XYZ UNIQUE' + System.now());
        insert testMilestone;
        testMilestone = [select Id, Name from Milestone1_Milestone__c where Name = :testMilestone.Name limit 1];
        
        Milestone1_Milestone__c testMilestone2 = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'UNIT TEST MILESTONE NAME ACB123XYZ UNIQUE' + System.now());
        insert testMilestone2;
        
        /*testMilestone tasks*/
        Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(testMilestone.Id); 
        task1.Start_Date__c = date.today().addDays(-5);
        task1.Due_Date__c = date.today().addDays(-5);   
        insert task1;
        
        Milestone1_Task__c task2 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task2.Start_Date__c = date.today().addDays(-4);
        task2.Due_Date__c = date.today().addDays(-4);
        task2.Predecessor_Task__c = task1.Id;
        insert task2;
        
        Milestone1_Task__c task3 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task3.Start_Date__c = date.today().addDays(-3);
        task3.Due_Date__c = date.today().addDays(-3);
        task3.Predecessor_Task__c = task2.Id;
        insert task3;
        
        Milestone1_Task__c task4 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task4.Start_Date__c = date.today().addDays(-2);
        task4.Due_Date__c = date.today().addDays(-2);
        task4.Predecessor_Task__c = task3.Id;
        insert task4;
        
        Milestone1_Task__c task5 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task5.Start_Date__c = date.today().addDays(-1);
        task5.Due_Date__c = date.today().addDays(-1);
        task5.Predecessor_Task__c = task4.Id;
        insert task5;
        
        Milestone1_Task__c task6 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task6.Start_Date__c = date.today();
        task6.Due_Date__c = date.today();
        task6.Predecessor_Task__c = task5.Id;
        insert task6;
        
        /*testMilestone2 tasks*/
        Milestone1_Task__c task7 = Milestone1_Test_Utility.sampleTask(testMilestone2.Id); 
        task7.Start_Date__c = date.today().addDays(-5);
        task7.Due_Date__c = date.today().addDays(-5);   
        insert task7;
        
        Milestone1_Task__c task8 = Milestone1_Test_Utility.sampleTask(testMilestone2.Id);
        task8.Start_Date__c = date.today().addDays(-4);
        task8.Due_Date__c = date.today().addDays(-4);
        task8.Predecessor_Task__c = task7.Id;
        insert task8;
        
        Milestone1_Task__c task9 = Milestone1_Test_Utility.sampleTask(testMilestone2.Id);
        task9.Start_Date__c = date.today().addDays(-3);
        task9.Due_Date__c = date.today().addDays(-3);
        task9.Predecessor_Task__c = task8.Id;
        insert task9;
        
        Milestone1_Task__c task10 = Milestone1_Test_Utility.sampleTask(testMilestone2.Id);
        task10.Start_Date__c = date.today().addDays(-2);
        task10.Due_Date__c = date.today().addDays(-2);
        task10.Predecessor_Task__c = task9.Id;
        insert task10;
        
        Milestone1_Task__c task11 = Milestone1_Test_Utility.sampleTask(testMilestone2.Id);
        task11.Start_Date__c = date.today().addDays(-1);
        task11.Due_Date__c = date.today().addDays(-1);
        task11.Predecessor_Task__c = task10.Id;
        insert task11;
        
        Milestone1_Task__c task12 = Milestone1_Test_Utility.sampleTask(testMilestone2.Id);
        task12.Start_Date__c = date.today();
        task12.Due_Date__c = date.today();
        task12.Predecessor_Task__c = task11.Id;
        insert task12;
                
        Milestone1_Export_Project_Controller controller = new Milestone1_Export_Project_Controller(new ApexPages.StandardController(testProject));
        controller.createExportXML();
        
        Document doc = [Select Name, Id, Body, ContentType From Document];
        doc.Name = 'Closed Won';
        doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = UserInfo.getUserId();
        upsert doc;
        
        insert acc; 

        opp.AccountId = acc.Id;
        insert opp;

        oldOpp.AccountId = acc.Id;
        insert oldOpp;
        oldMap = new map<id, sObject>{opp.Id => oldOpp};
                
        opp.StageName = 'Closed Won';
        update opp;
        opp = [select StageName, AccountId, Name from Opportunity where id =:opp.Id];
        newMap = new map<id, sObject>{opp.Id => opp};
        
        test.starttest();
        system.debug(logginglevel.error, [select Name from Opportunity where id =:opp.Id]);
        projCreationUtil.CreateChildProject(oldMap, newMap, new Map<string, object>{'projectCreationField' => 'StageName', 'projectLookupField1' => 'Opportunity__c', 'projectLookupField2' => 'Account__c', 'secondaryLookup' => 'AccountId', 'projectNamingConventionField' => 'Name'});
        test.stoptest();
        
        list<Milestone1_Project__c> projList = [select id, Name from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assertequals(1, projList.Size());
        
        proj = [select id, Name from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assert(proj != null, 'Did not insert Project');
        system.assertequals('test opp',  proj.name);
        
        milestones = [select id from Milestone1_Milestone__c where Project__c = :proj.Id];
        system.assertEquals(2, milestones.size());
        
        for(Milestone1_Milestone__c ms : milestones){
            tasks.AddAll([select id from Milestone1_Task__c where Project_Milestone__c = :ms.Id]);
        }
        system.assertEquals(12, tasks.size());
        
    
    }

    

   
    static testmethod void ShouldUpdateProjectKickoffToCurrentDate(){
        
        Milestone1_Project__c proj = new Milestone1_Project__c();
        list<Milestone1_Milestone__c> Milestones = new list<Milestone1_Milestone__c>();
        list<Milestone1_Task__c> Tasks = new list<Milestone1_Task__c>();
        Milestone1_Project_Creation_Utility projCreationUtil = new Milestone1_Project_Creation_Utility();
        map<id, sObject> oldMap = new map<id, sObject>();
        map<id, sObject> newMap = new map<id, sObject>();

        testProject.Kickoff__c = date.today().addDays(-5);
        testProject.DeadLine__c = date.today().addDays(-4);
        testProject.Status__c = 'Active';
        insert testProject;
        testProject = [select Id, Name from Milestone1_Project__c where Name = :testProject.Name limit 1];
         
        Milestone1_Milestone__c testMilestone = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'UNIT TEST MILESTONE NAME ACB123XYZ UNIQUE' + System.now());
        insert testMilestone;
        testMilestone = [select Id, Name from Milestone1_Milestone__c where Name = :testMilestone.Name limit 1];
        
        Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);      
        insert task1;
        
        Milestone1_Task__c task2 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        insert task2;
        
        Milestone1_Export_Project_Controller controller = new Milestone1_Export_Project_Controller(new ApexPages.StandardController(testProject));
        controller.createExportXML();
        
        Document doc = [Select Name, Id, Body, ContentType From Document];
        doc.Name = 'Closed Won';
        doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = UserInfo.getUserId();
        upsert doc; 
    
        insert acc; 

        opp.AccountId = acc.Id;
        insert opp;

        oldOpp.AccountId = acc.Id;
        insert oldOpp;
        oldMap = new map<id, sObject>{opp.Id => oldOpp};        
        
        opp.StageName = 'Closed Won';
        update opp;
        opp = [select StageName, AccountId, Name from Opportunity where id =:opp.Id];
        newMap = new map<id, sObject>{opp.Id => opp};
        
        test.starttest();
        system.debug(logginglevel.error, [select Name from Opportunity where id =:opp.Id]);
        projCreationUtil.CreateChildProject(oldMap, newMap, new Map<string, object>{'projectCreationField' => 'StageName', 'projectLookupField1' => 'Opportunity__c', 'projectLookupField2' => 'Account__c', 'secondaryLookup' => 'AccountId', 'projectNamingConventionField' => 'Name'});
        test.stoptest();
        
        list<Milestone1_Project__c> projList = [select id, Name from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assertequals(1, projList.Size());
        
        proj = [select id, Name, Kickoff__c, Deadline__c from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assert(proj != null, 'Did not insert Project');
        system.assertequals(date.today(),  proj.KickOff__c);
        system.assertequals(date.today().adddays(1), proj.Deadline__c);


    }
    
    static testmethod void shouldCascadeForwardDateShift(){
    	
    	Milestone1_Project__c proj = new Milestone1_Project__c();
        Milestone1_Milestone__c Milestone;
        list<Milestone1_Task__c> Tasks = new list<Milestone1_Task__c>();
        Milestone1_Project_Creation_Utility projCreationUtil = new Milestone1_Project_Creation_Utility();
        map<id, sObject> oldMap = new map<id, sObject>();
        map<id, sObject> newMap = new map<id, sObject>();

        testProject.Kickoff__c = date.today().addDays(-5);
        testProject.DeadLine__c = date.today().addDays(-1);
        testProject.Status__c = 'Active';
        insert testProject;
        testProject = [select Id, Name from Milestone1_Project__c where Name = :testProject.Name limit 1];
         
        Milestone1_Milestone__c testMilestone = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'UNIT TEST MILESTONE NAME ACB123XYZ UNIQUE' + System.now());
        testMilestone.Kickoff__c = date.today().addDays(-5);
        testMilestone.Deadline__c = date.today().addDays(-2);
        insert testMilestone;
        testMilestone = [select Id, Name from Milestone1_Milestone__c where Name = :testMilestone.Name limit 1];
        
        Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task1.Start_Date__c = date.today().addDays(-5);
        task1.Due_Date__c = date.today().addDays(-2);
        task1.Name = 'Task1';   
        insert task1;
        
        Milestone1_Task__c task2 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task2.Start_Date__c = date.today().addDays(-3);
        task2.Due_Date__c = date.today().addDays(-2);
        task2.Name = 'Task2';    
        insert task2;
        
        Milestone1_Export_Project_Controller controller = new Milestone1_Export_Project_Controller(new ApexPages.StandardController(testProject));
        controller.createExportXML();
        
        Document doc = [Select Name, Id, Body, ContentType From Document];
        doc.Name = 'Closed Won';
        doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = UserInfo.getUserId();
        upsert doc; 
    
        insert acc; 

        opp.AccountId = acc.Id;
        insert opp;

        oldOpp.AccountId = acc.Id;
        insert oldOpp;
        oldMap = new map<id, sObject>{opp.Id => oldOpp};        
        
        opp.StageName = 'Closed Won';
        update opp;
        opp = [select StageName, AccountId, Name from Opportunity where id =:opp.Id];
        newMap = new map<id, sObject>{opp.Id => opp};
        
        test.starttest();
        system.debug(logginglevel.error, [select Name from Opportunity where id =:opp.Id]);
        projCreationUtil.CreateChildProject(oldMap, newMap, new Map<string, object>{'projectCreationField' => 'StageName', 'projectLookupField1' => 'Opportunity__c', 'projectLookupField2' => 'Account__c', 'secondaryLookup' => 'AccountId', 'projectNamingConventionField' => 'Name'});
        test.stoptest();
        
        list<Milestone1_Project__c> projList = [select id, Name from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assertequals(1, projList.Size());
        
        proj = [select id, Name, Kickoff__c, Deadline__c from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assert(proj != null, 'Did not insert Project');
        system.assertequals(date.today(),  proj.KickOff__c);
        system.assertequals(date.today().addDays(4), proj.Deadline__c);
        
        milestone = [select id, KickOff__c, Deadline__c from Milestone1_Milestone__c where Project__c = :proj.Id limit 1];
        system.assertequals(date.today(), milestone.KickOff__c);
        system.assertequals(date.today().addDays(3), milestone.Deadline__c);
        
        task1 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task1'];
        system.assertequals(date.today(), task1.Start_Date__c);
        system.assertequals(date.today().addDays(3), task1.Due_Date__c);
        
        task2 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task2'];
        system.assertequals(date.today().addDays(2), task2.Start_Date__c);
        system.assertequals(date.today().addDays(3), task2.Due_Date__c);
        
    	
    }
    
    static testmethod void shouldCascadeBackwardDateShift(){
    	
    	Milestone1_Project__c proj = new Milestone1_Project__c();
        Milestone1_Milestone__c Milestone;
        list<Milestone1_Task__c> Tasks = new list<Milestone1_Task__c>();
        Milestone1_Project_Creation_Utility projCreationUtil = new Milestone1_Project_Creation_Utility();
        map<id, sObject> oldMap = new map<id, sObject>();
        map<id, sObject> newMap = new map<id, sObject>();

        testProject.Kickoff__c = date.today().addDays(5);
        testProject.DeadLine__c = date.today().addDays(1);
        testProject.Status__c = 'Active';
        insert testProject;
        testProject = [select Id, Name from Milestone1_Project__c where Name = :testProject.Name limit 1];
         
        Milestone1_Milestone__c testMilestone = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'UNIT TEST MILESTONE NAME ACB123XYZ UNIQUE' + System.now());
        testMilestone.Kickoff__c = date.today().addDays(5);
        testMilestone.Deadline__c = date.today().addDays(2);
        insert testMilestone;
        testMilestone = [select Id, Name from Milestone1_Milestone__c where Name = :testMilestone.Name limit 1];
        
        Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task1.Start_Date__c = date.today().addDays(5);
        task1.Due_Date__c = date.today().addDays(2);
        task1.Name = 'Task1';   
        insert task1;
        
        Milestone1_Task__c task2 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task2.Start_Date__c = date.today().addDays(3);
        task2.Due_Date__c = date.today().addDays(2);
        task2.Name = 'Task2';    
        insert task2;
        
        Milestone1_Export_Project_Controller controller = new Milestone1_Export_Project_Controller(new ApexPages.StandardController(testProject));
        controller.createExportXML();
        
        Document doc = [Select Name, Id, Body, ContentType From Document];
        doc.Name = 'Closed Won';
        doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = UserInfo.getUserId();
        upsert doc; 
    
        insert acc; 

        opp.AccountId = acc.Id;
        insert opp;

        oldOpp.AccountId = acc.Id;
        insert oldOpp;
        oldMap = new map<id, sObject>{opp.Id => oldOpp};        
        
        opp.StageName = 'Closed Won';
        update opp;
        opp = [select StageName, AccountId, Name from Opportunity where id =:opp.Id];
        newMap = new map<id, sObject>{opp.Id => opp};
        
        test.starttest();
        system.debug(logginglevel.error, [select Name from Opportunity where id =:opp.Id]);
        projCreationUtil.CreateChildProject(oldMap, newMap, new Map<string, object>{'projectCreationField' => 'StageName', 'projectLookupField1' => 'Opportunity__c', 'projectLookupField2' => 'Account__c', 'secondaryLookup' => 'AccountId', 'projectNamingConventionField' => 'Name'});
        test.stoptest();
        
        list<Milestone1_Project__c> projList = [select id, Name from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assertequals(1, projList.Size());
        
        proj = [select id, Name, Kickoff__c, Deadline__c from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assert(proj != null, 'Did not insert Project');
        system.assertequals(date.today(),  proj.KickOff__c);
        system.assertequals(date.today().addDays(-4), proj.Deadline__c);
        
        milestone = [select id, KickOff__c, Deadline__c from Milestone1_Milestone__c where Project__c = :proj.Id limit 1];
        system.assertequals(date.today(), milestone.KickOff__c);
        system.assertequals(date.today().addDays(-3), milestone.Deadline__c);
        
        task1 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task1'];
        system.assertequals(date.today(), task1.Start_Date__c);
        system.assertequals(date.today().addDays(-3), task1.Due_Date__c);
        
        task2 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task2'];
        system.assertequals(date.today().addDays(-2), task2.Start_Date__c);
        system.assertequals(date.today().addDays(-3), task2.Due_Date__c);
        
    	
    }
    
    static testmethod void shouldImportProjectUsingDefaultTemplateNameIfTemplateNotRenamed(){
    	
    	Milestone1_Project__c proj = new Milestone1_Project__c();
        Milestone1_Milestone__c Milestone;
        list<Milestone1_Task__c> Tasks = new list<Milestone1_Task__c>();
        Milestone1_Project_Creation_Utility projCreationUtil = new Milestone1_Project_Creation_Utility();
        map<id, sObject> oldMap = new map<id, sObject>();
        map<id, sObject> newMap = new map<id, sObject>();

        testProject.Kickoff__c = date.today().addDays(5);
        testProject.DeadLine__c = date.today().addDays(1);
        testProject.Status__c = 'Active';
        testProject.Name = 'Closed Won';
        insert testProject;
        testProject = [select Id, Name from Milestone1_Project__c where Name = :testProject.Name limit 1];
         
        Milestone1_Milestone__c testMilestone = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'UNIT TEST MILESTONE NAME ACB123XYZ UNIQUE' + System.now());
        testMilestone.Kickoff__c = date.today().addDays(5);
        testMilestone.Deadline__c = date.today().addDays(2);
        insert testMilestone;
        testMilestone = [select Id, Name from Milestone1_Milestone__c where Name = :testMilestone.Name limit 1];
        
        Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task1.Start_Date__c = date.today().addDays(5);
        task1.Due_Date__c = date.today().addDays(2);
        task1.Name = 'Task1';   
        insert task1;
        
        Milestone1_Task__c task2 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task2.Start_Date__c = date.today().addDays(3);
        task2.Due_Date__c = date.today().addDays(2);
        task2.Name = 'Task2'; 
        task2.Predecessor_Task__c = task1.Id;   
        insert task2;
        
        Milestone1_Export_Project_Controller controller = new Milestone1_Export_Project_Controller(new ApexPages.StandardController(testProject));
        controller.createExportXML();
        
        Document doc = [Select Name, Id, Body, ContentType From Document];
        system.debug(logginglevel.error, doc.name);
        doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = UserInfo.getUserId();
        upsert doc; 
    
        insert acc; 

        opp.AccountId = acc.Id;
        insert opp;

        oldOpp.AccountId = acc.Id;
        insert oldOpp;
        oldMap = new map<id, sObject>{opp.Id => oldOpp};        
        
        opp.StageName = 'Closed Won';
        update opp;
        opp = [select StageName, AccountId, Name from Opportunity where id =:opp.Id];
        newMap = new map<id, sObject>{opp.Id => opp};
        
        test.starttest();
        system.debug(logginglevel.error, [select Name from Opportunity where id =:opp.Id]);
        projCreationUtil.CreateChildProject(oldMap, newMap, new Map<string, object>{'projectCreationField' => 'StageName', 'projectLookupField1' => 'Opportunity__c', 'projectLookupField2' => 'Account__c', 'secondaryLookup' => 'AccountId', 'projectNamingConventionField' => 'Name'});
        test.stoptest();
        
        list<Milestone1_Project__c> projList = [select id, Name from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assertequals(1, projList.Size());
        
        proj = [select id, Name, Kickoff__c, Deadline__c from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assert(proj != null, 'Did not insert Project');
        system.assertequals(date.today(),  proj.KickOff__c);
        system.assertequals(date.today().addDays(-4), proj.Deadline__c);
        
        milestone = [select id, KickOff__c, Deadline__c from Milestone1_Milestone__c where Project__c = :proj.Id limit 1];
        system.assertequals(date.today(), milestone.KickOff__c);
        system.assertequals(date.today().addDays(-3), milestone.Deadline__c);
        
        task1 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task1'];
        system.assertequals(date.today(), task1.Start_Date__c);
        system.assertequals(date.today().addDays(-3), task1.Due_Date__c);
        
        task2 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task2'];
        system.assertequals(date.today().addDays(-2), task2.Start_Date__c);
        system.assertequals(date.today().addDays(-3), task2.Due_Date__c);
        
    	
    }
    
    static testmethod void shouldAllowNonAdminsToCreateProjects(){
    	
    	Profile profileUsed;
		User userObj;
		if(!Milestone1_Schema_Helper.isOrgChatterEnabled())
		return; //chatter is disabled - we can't run this test.
		
		//Setup project information
		Milestone1_Project__c proj = new Milestone1_Project__c();
        Milestone1_Milestone__c Milestone;
        list<Milestone1_Task__c> Tasks = new list<Milestone1_Task__c>();
        Milestone1_Project_Creation_Utility projCreationUtil = new Milestone1_Project_Creation_Utility();
        map<id, sObject> oldMap = new map<id, sObject>();
        map<id, sObject> newMap = new map<id, sObject>();

        testProject.Kickoff__c = date.today().addDays(5);
        testProject.DeadLine__c = date.today().addDays(1);
        testProject.Status__c = 'Active';
        testProject.Name = 'Closed Won';
        insert testProject;
        testProject = [select Id, Name from Milestone1_Project__c where Name = :testProject.Name limit 1];
         
        Milestone1_Milestone__c testMilestone = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'UNIT TEST MILESTONE NAME ACB123XYZ UNIQUE' + System.now());
        testMilestone.Kickoff__c = date.today().addDays(5);
        testMilestone.Deadline__c = date.today().addDays(2);
        insert testMilestone;
        testMilestone = [select Id, Name from Milestone1_Milestone__c where Name = :testMilestone.Name limit 1];
        
        Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task1.Start_Date__c = date.today().addDays(5);
        task1.Due_Date__c = date.today().addDays(2);
        task1.Name = 'Task1';   
        insert task1;
        
        Milestone1_Task__c task2 = Milestone1_Test_Utility.sampleTask(testMilestone.Id);
        task2.Start_Date__c = date.today().addDays(3);
        task2.Due_Date__c = date.today().addDays(2);
        task2.Name = 'Task2'; 
        task2.Predecessor_Task__c = task1.Id;   
        insert task2;
        
        Milestone1_Export_Project_Controller controller = new Milestone1_Export_Project_Controller(new ApexPages.StandardController(testProject));
        controller.createExportXML();
        
        Document doc = [Select Name, Id, Body, ContentType From Document];
        system.debug(logginglevel.error, doc.name);
        doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = UserInfo.getUserId();
        upsert doc; 
    
        insert acc; 

        opp.AccountId = acc.Id;
        insert opp;

        oldOpp.AccountId = acc.Id;
        insert oldOpp;
        oldMap = new map<id, sObject>{opp.Id => oldOpp};        
        
        opp.StageName = 'Closed Won';
        update opp;
        opp = [select StageName, AccountId, Name from Opportunity where id =:opp.Id];
        newMap = new map<id, sObject>{opp.Id => opp};

		//Create a non-admin user
		for( Profile p : [ Select Id, PermissionsViewAllData, Name from Profile
		where userLicense.licenseDefinitionKey = 'SFDC'
		AND PermissionsViewAllData = false
		AND PermissionsModifyAllData = false] ){
		profileUsed = p;
		break;
		}
		userObj = Milestone1_Test_Utility.createSFUser(profileUsed);
		system.debug('user Id for test ' + userObj.Id);
		Test.startTest();
		System.runAs(userObj) {
			
			
			system.debug(logginglevel.error, [select Name from Opportunity where id =:opp.Id]);
        	projCreationUtil.CreateChildProject(oldMap, newMap, new Map<string, object>{'projectCreationField' => 'StageName', 'projectLookupField1' => 'Opportunity__c', 'projectLookupField2' => 'Account__c', 'secondaryLookup' => 'AccountId', 'projectNamingConventionField' => 'Name'});
			
			
		}
		
		test.stopTest();
		
		list<Milestone1_Project__c> projList = [select id, Name from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assertequals(1, projList.Size());
        
        proj = [select id, Name, Kickoff__c, Deadline__c from Milestone1_Project__c where Opportunity__c = :opp.Id limit 1];
        system.assert(proj != null, 'Did not insert Project');
        system.assertequals(date.today(),  proj.KickOff__c);
        system.assertequals(date.today().addDays(-4), proj.Deadline__c);
        
        milestone = [select id, KickOff__c, Deadline__c from Milestone1_Milestone__c where Project__c = :proj.Id limit 1];
        system.assertequals(date.today(), milestone.KickOff__c);
        system.assertequals(date.today().addDays(-3), milestone.Deadline__c);
        
        task1 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task1'];
        system.assertequals(date.today(), task1.Start_Date__c);
        system.assertequals(date.today().addDays(-3), task1.Due_Date__c);
        
        task2 = [select id, Start_Date__c, Due_Date__c from Milestone1_Task__c where Project_Milestone__c = :milestone.Id and name = 'Task2'];
        system.assertequals(date.today().addDays(-2), task2.Start_Date__c);
        system.assertequals(date.today().addDays(-3), task2.Due_Date__c);
        
    }
    
/****************************************/

}