src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - Milestones are significant events in the life-cycle of a Project. You can also use them to track project phases. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for completing the task. Defaults to current user if left blank.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Milestone1_Project_Utility_Behavior.cls
@istest
public class Milestone1_Project_Utility_Behavior {
	
private static Milestone1_Project__c testProject = Milestone1_Test_Utility.sampleProject('Closed Won' + System.now());
private static Milestone1_Milestone__c m1;
private static Milestone1_Milestone__c m2;
private static User user1;
private static User user2;
private static User user3;


static {
	
		user1 = Milestone1_Test_Utility.createSFUser();
		user2 = Milestone1_Test_Utility.createSFUser();
		user3 = Milestone1_Test_Utility.createSFUser();
		
    	testProject.Kickoff__c = date.today().addDays(-5);
        testProject.Deadline__c = date.today();
        testProject.OwnerId = user1.Id;
        insert testProject;
        
        m1 = Milestone1_Test_Utility.sampleMilestone(testProject);
		m2 = Milestone1_Test_Utility.sampleMilestone(testProject);
		m1.OwnerId = user2.Id;
		m1.Complete__c = false;
        insert m1;
        m2.OwnerId = user1.Id;
        m2.Complete__c = false;
		insert m2;
		
}
	
/***************************************************************************************
	
shouldUpdateMilestoneOwners - Given a project with milestones, WHEN the parent project has
							 had owner changed, THEN all incomplete, child milestones having 
							 the same old owner should be updated and with completed milestones left alone.
	
****************************************************************************************/
	static testmethod void shouldUpdateMilestoneOwners() 
	{
		
		Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(m1.id);
		Milestone1_Task__c task2 = Milestone1_Test_Utility.sampleTask(m2.id);
		Milestone1_Task__c task3 = Milestone1_Test_Utility.sampleTask(m2.id);
		Milestone1_Task__c task4 = Milestone1_Test_Utility.sampleTask(m2.id);

		task1.Assigned_To__c = user1.Id;
		insert task1;
		
		task2.Assigned_To__c = user1.Id;
		insert task2;
		task3.Assigned_To__c = user2.Id;
		insert task3;
		task4.Assigned_To__c = user1.Id;
		task4.Complete__c = true;
		insert task4;

		test.startTest();
		testProject.OwnerId = user3.Id;
		update testProject;
		test.stopTest();
		
		m1 = [SELECT Id, OwnerId, project__c FROM Milestone1_Milestone__c WHERE id = :m1.id];
		m2 = [SELECT Id, OwnerId, project__c FROM Milestone1_Milestone__c WHERE id = :m2.id];
		
		testproject = [SELECT OwnerId FROM Milestone1_Project__c WHERE id =: testproject.id];
		
		//Owner of m1 did not change because it was a different user
		System.assertEquals(user2.Id, m1.OwnerId);
		//owner changed for incomplete milestones having same name
		System.assertEquals(user3.Id, m2.OwnerId);
		
		task1 = [select id, assigned_to__c from Milestone1_Task__c where id = :task1.id];
		task2 = [select id, assigned_to__c from Milestone1_Task__c where id = :task2.id];
		task3 = [select id, assigned_to__c from Milestone1_Task__c where id = :task3.id];
		task4 = [select id, assigned_to__c from Milestone1_Task__c where id = :task4.id];
		
		system.assertEquals(user1.Id, task1.Assigned_To__c);
		system.assertEquals(user3.Id, task2.Assigned_To__c);
		system.assertEquals(user2.Id, task3.Assigned_To__c);
		system.assertEquals(user1.Id, task4.Assigned_To__c);

	}

}