src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - Milestones are significant events in the life-cycle of a Project. You can also use them to track project phases. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Community Edition - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>When should this task start by?</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Milestone2_Project_Task_RL_Behavior.cls
/***************************************************************

	shouldAccesFieldSet - GIVEN a project, milestones, and task exists
						  WHEN the user visits a milestone record
						  THEN the fieldset created for task should be visible

***************************************************************/

@istest(SeeAllData=true)
public class Milestone2_Project_Task_RL_Behavior {
	
	private static Milestone1_Project__c testProject = Milestone1_Test_Utility.sampleProject('Closed Won' + System.now());
    private static Milestone1_Milestone__c testMilestone = new Milestone1_Milestone__c();
    
    static{
    	insert testProject;
		
		testMilestone = Milestone1_Test_Utility.sampleMilestone(testProject.Id,null,'Milestone 1' + System.now());
        testMilestone.Kickoff__c = date.today().addDays(-5);
        testMilestone.Deadline__c = date.today();
        insert testMilestone;
        
        Milestone1_Task__c task1 = Milestone1_Test_Utility.sampleTask(testMilestone.Id); 
        task1.Start_Date__c = date.today().addDays(-5);
        task1.Due_Date__c = date.today().addDays(-5);   
        insert task1;
    	
    }
	
	static testmethod void ShouldAccessFieldSet(){
		ApexPages.StandardController sc = new ApexPages.StandardController(testMilestone);
        Milestone2_Project_Task_RL_Controller testController = new Milestone2_Project_Task_RL_Controller(sc);
        
        List<Schema.FieldSetMember> fieldset = testController.getFieldSetMembers();
        
        system.assert(fieldset != null, 'There is no field set');
	}

}